services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=admin
      - DB_PASS=1234
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234

volumes:
  dev-db-data:
